import sys,sce
class Tropeognathus_Character_BP(sce.Dinos):
   def __init__(self):
       super().__init__(self)
       name = 'Tropeognathus'
       blueprintPath = '/Game/PrimalEarth/Dinos/Tropeognathus/Tropeognathus_Character_BP.Tropeognathus_Character_BP'
       variants = ['CrystalIsles']
       isFlyer = True
       fullStatsRaw = [[360, 0.2, 0.243, 0.5, 0], [250, 0.05, 0.05, 0, 0], [450, 0.06, 0, 0.5, 0], [150, 0.1, 0.1, 0, 0], [1600, 0.1, 0.1, 0, 0.15], None, None, [340, 0.02, 0.04, 0, 0], [1, 0.05, 0.1, 0.5, 0.4], [1, 0, 0.01, 0.365, 0], None, None]
       statImprintMult = [0.2, 0, 0.2, 0, 0.2, 0.2, 0, 0.2, 0.2, 0, 0, 0]
       immobilizedBy = ['Bola', 'Chain Bola', 'Bear Trap', 'Large Bear Trap', 'Plant Species Y']
       breeding = {'gestationTime': 0, 'incubationTime': 5999.52004, 'eggTempMin': 29, 'eggTempMax': 32, 'maturationTime': 196078.431, 'matingCooldownMin': 64800, 'matingCooldownMax': 172800}
       colors = [{'name': 'Main', 'colors': ['BigFoot5', 'Black', 'BlackSands', 'BurntSienna', 'Coral', 'DarkCement', 'DarkTurquoise', 'DarkWarmGray', 'Dino Light Brown', 'Dino Light Green', 'Dino Light Red', 'Dino Medium Blue', 'DragonFire', 'DragonGreen1', 'DragonGreen3', 'GreenSlate', 'MediumAutumn', 'MediumTurquoise', 'MidnightBlue', 'NearBlack', 'NearWhite', 'Turquoise', 'WyvernBlue0', 'WyvernBlue1', 'WyvernPurple0', 'WyvernPurple1']}, {'name': 'Wing Stripes Bottom', 'colors': ['BigFoot5', 'Dino Light Blue', 'Dino Light Brown', 'Dino Light Green', 'Dino Light Orange', 'Dino Light Purple', 'Dino Light Red', 'Dino Light Yellow', 'Dino Medium Brown', 'DragonBase0', 'DragonBase1', 'DragonGreen0', 'DragonGreen1', 'DragonGreen3', 'Light Grey', 'LightCement', 'LightPink', 'MediumTurquoise', 'NearWhite', 'Peach', 'WyvernBlue0', 'WyvernBlue1']}, {'name': 'Beak Stripes', 'colors': ['Coral', 'Dino Deep Blue', 'Dino Light Orange', 'Dino Light Red', 'Dino Medium Blue', 'DragonFire', 'Lavender', 'LeafGreen', 'Light Green', 'Light Orange', 'Light Yellow', 'LightAutumn', 'LightCement', 'LightPink', 'Magenta', 'MediumAutumn', 'Mint', 'None', 'Peach', 'PowderBlue', 'Teal', 'Turquoise', 'WyvernBlue0', 'WyvernPurple1']}, {'name': 'Fur', 'colors': ['BigFoot0', 'BigFoot4', 'BigFoot5', 'BlackSands', 'BurntSienna', 'DarkWarmGray', 'Dino Albino', 'Dino Dark Brown', 'Dino Darker Grey', 'Dino Light Brown', 'Dino Medium Brown', 'DragonBase0', 'DragonBase1', 'DragonFire', 'DragonGreen3', 'LightAutumn', 'LightWarmGray', 'NearBlack', 'None', 'WyvernBlue0', 'WyvernBlue1', 'WyvernPurple0']}, {'name': 'Belly Light', 'colors': ['BigFoot0', 'BigFoot4', 'BigFoot5', 'Dino Light Blue', 'Dino Light Brown', 'Dino Light Green', 'Dino Light Orange', 'Dino Light Purple', 'Dino Light Red', 'Dino Light Yellow', 'DragonBase0', 'DragonBase1', 'DragonGreen2', 'Light Grey', 'Light Red', 'Light Yellow', 'LightCement', 'LightWarmGray', 'NearWhite', 'WyvernPurple1']}, {'name': 'Top Stripes', 'colors': ['BigFoot5', 'Dino Light Blue', 'Dino Light Brown', 'Dino Light Green', 'Dino Light Orange', 'Dino Light Purple', 'Dino Light Red', 'Dino Light Yellow', 'Dino Medium Brown', 'DragonBase0', 'DragonBase1', 'DragonGreen0', 'DragonGreen1', 'DragonGreen3', 'Light Grey', 'LightCement', 'LightPink', 'MediumTurquoise', 'NearWhite', 'Peach', 'WyvernBlue0', 'WyvernBlue1']}]
       taming = {'nonViolent': True, 'violent': False, 'tamingIneffectiveness': 3.125, 'affinityNeeded0': 2200, 'affinityIncreasePL': 100, 'wakeAffinityMult': 1.65, 'wakeFoodDeplMult': 0.5, 'foodConsumptionBase': 0.001543, 'foodConsumptionMult': 216.0294}
       boneDamageAdjusters = {'c_head': 3}
       TamedBaseHealthMultiplier = 1
       displayedStats = 927
