import sys,sce
class BionicStego_Character_BP(sce.Tek Creatures):
   def __init__(self):
       super().__init__(self)
       name = 'Tek Stegosaurus'
       blueprintPath = '/Game/PrimalEarth/Dinos/Stego/BionicStego_Character_BP.BionicStego_Character_BP'
       fullStatsRaw = [[650, 0.2, 0.27, 0.5, 0], [300, 0.1, 0.1, 0, 0], [500, 0.06, 0, 0.5, 0], [150, 0.1, 0.1, 0, 0], [6000, 0.1, 0.1, 0, 0], None, None, [500, 0.02, 0.04, 0, 0], [1, 0.05, 0.1, 0.5, 0.4], [1, 0, 0.02, 0.964, 0], None, None]
       immobilizedBy = ['Chain Bola', 'Large Bear Trap', 'Plant Species Y']
       breeding = {'gestationTime': 0, 'incubationTime': 9999.20006, 'eggTempMin': 22, 'eggTempMax': 28, 'maturationTime': 185185.185, 'matingCooldownMin': 64800, 'matingCooldownMax': 172800}
       colors = [{'name': 'Inner Body', 'colors': ['Dark Green', 'Dino Dark Brown', 'Dino Dark Green', 'Dino Dark Yellow', 'Dino Darker Grey', 'Dino Light Blue', 'Dino Light Brown', 'Dino Light Green', 'Dino Light Yellow', 'Dino Medium Brown', 'Dino Medium Green', 'DragonGreen0', 'DragonGreen1', 'GragonGreen2', 'Light Green', 'Light Yellow', 'NearBlack', 'NearWhite']}, {'name': 'Spine', 'colors': ['Dark Green', 'Dino Dark Brown', 'Dino Dark Green', 'Dino Dark Yellow', 'Dino Darker Grey', 'Dino Light Blue', 'Dino Light Brown', 'Dino Light Green', 'Dino Light Yellow', 'Dino Medium Brown', 'Dino Medium Green', 'DragonGreen0', 'DragonGreen1', 'GragonGreen2', 'Light Green', 'Light Yellow', 'NearBlack', 'NearWhite']}, {'name': 'Body', 'colors': ['Dark Green', 'Dino Dark Brown', 'Dino Dark Green', 'Dino Dark Yellow', 'Dino Darker Grey', 'Dino Light Blue', 'Dino Light Brown', 'Dino Light Green', 'Dino Light Yellow', 'Dino Medium Brown', 'Dino Medium Green', 'DragonGreen0', 'DragonGreen1', 'GragonGreen2', 'Light Green', 'Light Yellow', 'NearBlack', 'NearWhite']}, {'name': 'Legs and Head', 'colors': ['Dark Green', 'Dino Dark Brown', 'Dino Dark Green', 'Dino Dark Yellow', 'Dino Darker Grey', 'Dino Light Blue', 'Dino Light Brown', 'Dino Light Green', 'Dino Light Yellow', 'Dino Medium Brown', 'Dino Medium Green', 'DragonGreen0', 'DragonGreen1', 'GragonGreen2', 'Light Green', 'Light Yellow', 'NearBlack', 'NearWhite']}, {'name': 'Leg Tops and Spike Plate', 'colors': ['Dark Green', 'Dino Dark Brown', 'Dino Dark Green', 'Dino Dark Yellow', 'Dino Darker Grey', 'Dino Light Blue', 'Dino Light Brown', 'Dino Light Green', 'Dino Light Yellow', 'Dino Medium Brown', 'Dino Medium Green', 'DragonGreen0', 'DragonGreen1', 'GragonGreen2', 'Light Green', 'Light Yellow', 'NearBlack', 'NearWhite']}, {'name': 'Emissive and Spike Tops', 'colors': ['Dino Albino', 'Dino Light Blue', 'Dino Light Purple', 'Light Green', 'Light Orange', 'Light Red', 'Light Yellow']}]
       taming = {'nonViolent': False, 'violent': True, 'tamingIneffectiveness': 0.1, 'affinityNeeded0': 6000, 'affinityIncreasePL': 300, 'torporDepletionPS0': 0.3, 'foodConsumptionBase': 0.005341, 'foodConsumptionMult': 208.0343}
       boneDamageAdjusters = {'Cnt_Head_JNT_SKL': 1.67, 'Cnt_Jaw_JNT_SKL': 1.67, 'Cnt_Neck_004_JNT_SKL': 1.67, 'Cnt_Spine_002_JNT_SKL': 0.7, 'Cnt_Spine_001_JNT_SKL': 0.7, 'Cnt_Spine_000_JNT_SKL': 0.7, 'Cnt_Spine_003_JNT_SKL': 0.7, 'Cnt_Tail_000_JNT_SKL': 0.7}
       TamedBaseHealthMultiplier = 1
       displayedStats = 927
